### ISSUE TITLE
Too many Fiducial markers on the board

### ISSUE THREAD

**Issue by esden** [felixheld/AXIOM-photonSDI-hw#1]
Just took a look at the board. You have 4 fiducial markers in all corners of the board. For manufacturing purposes you only want to have 3 fiducial markers, this will prevent situations when the board is inserted into the P&P machine the wrong way around, and will still provide the same amount of accuracy.

You also want to place the markers on the back side and top side of the board in a way that will result in a fiducial marker search error when you insert the board up-side-down.

Thank you for publishing the board design! Looking forward to the new SDI plugin. :D

**Comment by felixheld** [comment]
Ah, that's why most designs use only 3 fiducial markers per side. In most of my previous designs I only used 3, because I didn't really have space for the fourth.
Thanks for the heads up; I'll fix that soon in the design.

**Comment by esden** [comment]
No problem. For some reason it is hard to get to this kind of "best practices" information. I took me years of board designs with too many evenly spaced fiducial markers until someone told me that I am doing it wrong. This is why I decided to let you know about it. :)

**Comment by felixheld** [comment]
I'd say that I've fixed the issue in https://github.com/felixheld/AXIOM-photonSDI-hw/commit/eec5be62577b4db7fad171903f9c695ea26a3ccf would be good though if you could have a look again if I understood that correctly

**Comment by esden** [comment]
Sorry for the delay. I finally had time to take a look. It looks good to me. I would consider the issue resolved. 😸  👍
