### ISSUE TITLE
Swapped Pins

### ISSUE THREAD

**Issue by pixellon** [felixheld/AXIOM-photonSDI-hw#2]
I see some swapped pins in the SDI RX and Silicon labs clock generator. Are they by design ? if so is there a reason why are they swapped ?

**Comment by felixheld** [comment]
This is intended and to improve routability and signal integrity. For the differential SDI signal this makes no difference as it is an NRZI encoded signal (information is encodes as level change or absence of a level change) and the clock has 50% duty cycle and I think that the clock could even be inverted on at least one of the ends (not sure about the last bit, but I don't expect to need that tbh).
